# Generated by Django 4.1.4 on 2023-07-21 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bootcamps', '0003_alter_bootcampinscripcion_bootcamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=500)),
                ('upload', models.FileField(upload_to='campus/asignaciones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AsignacionBootcamp',
                'verbose_name_plural': 'AsignacionBootcamps',
            },
        ),
        migrations.CreateModel(
            name='EntregasBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='campus/entregas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='campus.asignacionbootcamp')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EntregasBootcamp',
                'verbose_name_plural': 'EntregasBootcamps',
            },
        ),
        migrations.CreateModel(
            name='SesionBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootcamps.bootcamp')),
            ],
            options={
                'verbose_name': 'seccionBootcamp',
                'verbose_name_plural': 'seccionBootcampS',
            },
        ),
        migrations.CreateModel(
            name='RecursoBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=500)),
                ('upload', models.FileField(upload_to='campus/cargas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurso', to='campus.sesionbootcamp')),
            ],
            options={
                'verbose_name': 'RecursoBootcamp',
                'verbose_name_plural': 'RecursoBootcamps',
            },
        ),
        migrations.CreateModel(
            name='PromedioBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prom_inscripcion', to='bootcamps.bootcampinscripcion')),
            ],
            options={
                'verbose_name': 'PromedioBootcamp',
                'verbose_name_plural': 'PromedioBootcamps',
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_receptor', models.IntegerField(blank=True, null=True)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NotificacionesBootcamp',
                'verbose_name_plural': 'NotificacionesBootcamps',
            },
        ),
        migrations.CreateModel(
            name='NotasBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
                ('calificacion', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota', to='campus.entregasbootcamp')),
            ],
            options={
                'verbose_name': 'NotasBootcamp',
                'verbose_name_plural': 'NotasBootcamps',
            },
        ),
        migrations.CreateModel(
            name='EventosBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('color_evento', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EventosBootcamp',
                'verbose_name_plural': 'EventosBootcamps',
            },
        ),
        migrations.CreateModel(
            name='AssistBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_clase', models.DateTimeField(blank=True)),
                ('asistencia', models.BooleanField(default=False, verbose_name='Assist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info_usuario', models.ManyToManyField(related_name='assist', to='bootcamps.bootcampinscripcion')),
            ],
            options={
                'verbose_name': 'AssistBootcamp',
                'verbose_name_plural': 'AssistBootcamps',
            },
        ),
        migrations.AddField(
            model_name='asignacionbootcamp',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='campus.sesionbootcamp'),
        ),
    ]
