# Generated by Django 4.1.4 on 2023-02-28 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='bootcamps')),
                ('requisito1', models.CharField(max_length=100)),
                ('requisito2', models.CharField(blank=True, max_length=100)),
                ('requisito3', models.CharField(blank=True, max_length=100)),
                ('requisito4', models.CharField(blank=True, max_length=100)),
                ('requisito5', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bootcamp',
                'verbose_name_plural': 'bootcamps',
            },
        ),
        migrations.CreateModel(
            name='ProgramasAcademico',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo_categoria',
                'verbose_name_plural': 'Tipo_categorias',
            },
        ),
        migrations.CreateModel(
            name='BootcampInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('bootcamp', models.ManyToManyField(to='bootcamps.bootcamp')),
                ('carrera', models.ManyToManyField(to='bootcamps.programasacademico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BootcampInscripcion',
                'verbose_name_plural': 'BootcampInscripciones',
            },
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='categoria',
            field=models.ManyToManyField(to='bootcamps.tipo_categoria'),
        ),
    ]
