# Generated by Django 4.1.4 on 2023-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0002_alter_bootcampinscripcion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcampinscripcion',
            name='bootcamp',
            field=models.ManyToManyField(related_name='bootcamp', to='bootcamps.bootcamp'),
        ),
    ]
